/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.TaiKhoanDAO;
import Entity.TaiKhoan;
import Helper.Auth;
import Helper.MsgBox;

/**
 *
 * @author Admin
 */
public class DangNhapJFrame extends javax.swing.JDialog {

        /**
         * Creates new form DangNhapJFrame
         */
        public DangNhapJFrame(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                init();
        }

        void init() {
                setLocationRelativeTo(null);
        }
        TaiKhoanDAO tkDAO = new TaiKhoanDAO();

        void login() {
                if (txtTenDangNhap.getText().trim().isEmpty()) {
                        MsgBox.alert(this, "Nhập tên tài khoản");
                        txtTenDangNhap.requestFocus();
                        return;
                }
                if (txtMatKhau.getText().trim().isEmpty()) {
                        MsgBox.alert(this, "Nhập mật khẩu");
                        txtMatKhau.requestFocus();
                        return;
                }

                String tenDangNhap = txtTenDangNhap.getText();
                String matKhau = new String(txtMatKhau.getPassword());

                TaiKhoan tk = tkDAO.SelectByID(tenDangNhap);
                if (tk == null) {
                        MsgBox.alert(this, "Sai tên đăng nhập !");
                } else if (!matKhau.equals(tk.getMatKhau())) {
                        MsgBox.alert(this, "Sai tên mật khẩu !");
                } else {
                        Auth.user = tk;
                        MsgBox.alert(this, "Đăng nhập thành công !");
                        this.dispose();
                }

        }

        /**
         *
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                txtTenDangNhap = new javax.swing.JTextField();
                txtMatKhau = new javax.swing.JPasswordField();
                chkNhoMatKhau = new javax.swing.JCheckBox();
                jLabel5 = new javax.swing.JLabel();
                btnDangNhap = new javax.swing.JButton();
                btnHuy = new javax.swing.JButton();
                jLabel6 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("Đăng Nhập");
                setResizable(false);

                jLabel1.setText("Logo");

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel3.setText("Tên Đăng Nhập ");

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel4.setText("Mật Khẩu ");

                txtTenDangNhap.setBackground(new java.awt.Color(240, 240, 240));

                txtMatKhau.setBackground(new java.awt.Color(240, 240, 240));

                chkNhoMatKhau.setText("Nhớ mật khẩu");

                jLabel5.setText("Quên mật khẩu");

                btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Login.png"))); // NOI18N
                btnDangNhap.setText("Đăng nhập");
                btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDangNhapActionPerformed(evt);
                        }
                });

                btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit button.png"))); // NOI18N
                btnHuy.setText("Hủy");

                jLabel6.setText("jLabel6");
                jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(null));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(224, 224, 224)
                                                .addComponent(jLabel3))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(227, 227, 227)
                                                .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTenDangNhap)
                                        .addComponent(txtMatKhau)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkNhoMatKhau)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                                .addComponent(jLabel5))
                                        .addComponent(btnDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(chkNhoMatKhau)
                                                        .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnDangNhap)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnHuy)))
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
            // TODO add your handling code here:
            login();
    }//GEN-LAST:event_btnDangNhapActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                DangNhapJFrame dialog = new DangNhapJFrame(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnDangNhap;
        private javax.swing.JButton btnHuy;
        private javax.swing.JCheckBox chkNhoMatKhau;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPasswordField txtMatKhau;
        private javax.swing.JTextField txtTenDangNhap;
        // End of variables declaration//GEN-END:variables
}
