/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Helper.Auth;
import Helper.MsgBox;

/**
 *
 * @author Admin
 */
public class GiaoDienChinhJFrame extends javax.swing.JFrame {

        /**
         * Creates new form GiaoDienChinhJFrame
         */
        public GiaoDienChinhJFrame() {
                initComponents();
                init();
        }

        void init() {
                setLocationRelativeTo(null);
                new DangNhapJFrame(this, true).setVisible(true);
        }

        void openNhanVien() {
                if (!Auth.isLogin()) {
                        MsgBox.alert(this, "Vui lòng đăng nhập");
                } else if (Auth.user.getVaiTro() == 5) {
                        new NhanVienJFrame(this, true).setVisible(true);
                } else {
                        MsgBox.alert(this, "Chỉ có quyền hạn nhân sự mới được sử dụng chức năng này !");
                }
        }

        void openDangXuat() {
                Auth.clear();
                new DangNhapJFrame(this, true).setVisible(true);
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel5 = new javax.swing.JPanel();
                tab = new javax.swing.JTabbedPane();
                jPanel2 = new javax.swing.JPanel();
                jPanel11 = new javax.swing.JPanel();
                btnDangXuat = new javax.swing.JButton();
                btnDoiMatKhau = new javax.swing.JButton();
                btnThoat = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jPanel10 = new javax.swing.JPanel();
                btnPhongTrong = new javax.swing.JButton();
                btnNgayHetHan = new javax.swing.JButton();
                btnSapXep = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jPanel21 = new javax.swing.JPanel();
                btnDanhSach = new javax.swing.JButton();
                btnDoThatLac = new javax.swing.JButton();
                jLabel34 = new javax.swing.JLabel();
                jPanel22 = new javax.swing.JPanel();
                btnDatPhong = new javax.swing.JButton();
                btnKhachDoan = new javax.swing.JButton();
                btnTraPhong = new javax.swing.JButton();
                btnThemPhong = new javax.swing.JButton();
                jLabel35 = new javax.swing.JLabel();
                jPanel23 = new javax.swing.JPanel();
                btnDichVu = new javax.swing.JButton();
                jLabel36 = new javax.swing.JLabel();
                jPanel24 = new javax.swing.JPanel();
                btnTaiKhoan = new javax.swing.JButton();
                btnNhanVien = new javax.swing.JButton();
                jLabel37 = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                jPanel25 = new javax.swing.JPanel();
                btnBaoCao = new javax.swing.JButton();
                btnCongNo = new javax.swing.JButton();
                jLabel41 = new javax.swing.JLabel();
                jPanel26 = new javax.swing.JPanel();
                btnQuanLyKho = new javax.swing.JButton();
                jLabel39 = new javax.swing.JLabel();
                jPanel27 = new javax.swing.JPanel();
                btnNhatKy = new javax.swing.JButton();
                jLabel40 = new javax.swing.JLabel();
                jPanel20 = new javax.swing.JPanel();
                jPanel28 = new javax.swing.JPanel();
                jButton20 = new javax.swing.JButton();
                jButton21 = new javax.swing.JButton();
                jButton22 = new javax.swing.JButton();
                tabs = new javax.swing.JTabbedPane();
                jPanel6 = new javax.swing.JPanel();
                jPanel12 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jPanel7 = new javax.swing.JPanel();
                jPanel8 = new javax.swing.JPanel();
                jPanel9 = new javax.swing.JPanel();
                jPanel19 = new javax.swing.JPanel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Phần Mềm Quản Lý Khách Sạn");
                setBackground(new java.awt.Color(255, 255, 255));

                jPanel2.setBackground(new java.awt.Color(204, 255, 255));
                jPanel2.setToolTipText("");

                jPanel11.setBackground(new java.awt.Color(204, 255, 204));

                btnDangXuat.setBackground(new java.awt.Color(255, 255, 153));
                btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnDangXuat.setForeground(new java.awt.Color(255, 51, 51));
                btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Log out.png"))); // NOI18N
                btnDangXuat.setText("Đăng xuất");
                btnDangXuat.setFocusable(false);
                btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnDangXuat.setOpaque(false);
                btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDangXuatActionPerformed(evt);
                        }
                });

                btnDoiMatKhau.setBackground(new java.awt.Color(255, 255, 153));
                btnDoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnDoiMatKhau.setForeground(new java.awt.Color(255, 51, 51));
                btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Refresh.png"))); // NOI18N
                btnDoiMatKhau.setText("Đổi mật khẩu");
                btnDoiMatKhau.setFocusable(false);
                btnDoiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnDoiMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                btnThoat.setBackground(new java.awt.Color(255, 255, 153));
                btnThoat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnThoat.setForeground(new java.awt.Color(255, 51, 51));
                btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_24.png"))); // NOI18N
                btnThoat.setText("Thoát");
                btnThoat.setFocusable(false);
                btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnThoat.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnThoatActionPerformed(evt);
                        }
                });

                jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel1.setText("                                      Tài khoản");

                javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
                jPanel11.setLayout(jPanel11Layout);
                jPanel11Layout.setHorizontalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel11Layout.createSequentialGroup()
                                                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDoiMatKhau)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel11Layout.setVerticalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addContainerGap())
                );

                jPanel10.setBackground(new java.awt.Color(204, 255, 204));

                btnPhongTrong.setBackground(new java.awt.Color(255, 255, 153));
                btnPhongTrong.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnPhongTrong.setForeground(new java.awt.Color(255, 51, 51));
                btnPhongTrong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Home.png"))); // NOI18N
                btnPhongTrong.setText("Phòng trống");
                btnPhongTrong.setFocusable(false);
                btnPhongTrong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnPhongTrong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                btnNgayHetHan.setBackground(new java.awt.Color(255, 255, 153));
                btnNgayHetHan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnNgayHetHan.setForeground(new java.awt.Color(255, 51, 51));
                btnNgayHetHan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Date.png"))); // NOI18N
                btnNgayHetHan.setText("Ngày hết hạn");
                btnNgayHetHan.setFocusable(false);
                btnNgayHetHan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnNgayHetHan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                btnSapXep.setBackground(new java.awt.Color(255, 255, 153));
                btnSapXep.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnSapXep.setForeground(new java.awt.Color(255, 51, 51));
                btnSapXep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sort-ascending-icon.png"))); // NOI18N
                btnSapXep.setText("Sắp xếp");
                btnSapXep.setFocusable(false);
                btnSapXep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnSapXep.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel2.setText("                                           Bộ lọc");

                javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                jPanel10.setLayout(jPanel10Layout);
                jPanel10Layout.setHorizontalGroup(
                        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addComponent(btnPhongTrong)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnNgayHetHan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel10Layout.setVerticalGroup(
                        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnPhongTrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNgayHetHan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSapXep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(518, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22))
                );

                tab.addTab("Hệ Thống", jPanel2);

                jPanel3.setBackground(new java.awt.Color(204, 255, 255));

                jPanel21.setBackground(new java.awt.Color(204, 255, 204));

                btnDanhSach.setBackground(new java.awt.Color(255, 255, 153));
                btnDanhSach.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnDanhSach.setForeground(new java.awt.Color(255, 51, 51));
                btnDanhSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/List.png"))); // NOI18N
                btnDanhSach.setText("Danh sách");
                btnDanhSach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnDanhSach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                btnDoThatLac.setBackground(new java.awt.Color(255, 255, 153));
                btnDoThatLac.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnDoThatLac.setForeground(new java.awt.Color(255, 51, 51));
                btnDoThatLac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/case-icon.png"))); // NOI18N
                btnDoThatLac.setText("Đồ thất lạc");
                btnDoThatLac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnDoThatLac.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                jLabel34.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel34.setText("             Quản Lý Khách Hàng");

                javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
                jPanel21.setLayout(jPanel21Layout);
                jPanel21Layout.setHorizontalGroup(
                        jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel21Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel21Layout.createSequentialGroup()
                                                .addComponent(btnDanhSach)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnDoThatLac)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel21Layout.setVerticalGroup(
                        jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel21Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDanhSach)
                                        .addComponent(btnDoThatLac))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel34)
                                .addContainerGap())
                );

                jPanel22.setBackground(new java.awt.Color(204, 255, 204));

                btnDatPhong.setBackground(new java.awt.Color(255, 255, 153));
                btnDatPhong.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnDatPhong.setForeground(new java.awt.Color(255, 51, 51));
                btnDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Date.png"))); // NOI18N
                btnDatPhong.setText("Đặt phòng");
                btnDatPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnDatPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                btnKhachDoan.setBackground(new java.awt.Color(255, 255, 153));
                btnKhachDoan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnKhachDoan.setForeground(new java.awt.Color(255, 51, 51));
                btnKhachDoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User group.png"))); // NOI18N
                btnKhachDoan.setText("Khách đoàn");
                btnKhachDoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnKhachDoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                btnTraPhong.setBackground(new java.awt.Color(255, 255, 153));
                btnTraPhong.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnTraPhong.setForeground(new java.awt.Color(255, 51, 51));
                btnTraPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Log out.png"))); // NOI18N
                btnTraPhong.setText("Trả phòng");
                btnTraPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnTraPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                btnThemPhong.setBackground(new java.awt.Color(255, 255, 153));
                btnThemPhong.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnThemPhong.setForeground(new java.awt.Color(255, 51, 51));
                btnThemPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Home.png"))); // NOI18N
                btnThemPhong.setText("Thêm phòng");
                btnThemPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnThemPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                jLabel35.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel35.setText("                                                 Quản Lý Phòng");

                javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
                jPanel22.setLayout(jPanel22Layout);
                jPanel22Layout.setHorizontalGroup(
                        jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel22Layout.createSequentialGroup()
                                                .addComponent(btnDatPhong)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnKhachDoan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnTraPhong)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnThemPhong)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel22Layout.setVerticalGroup(
                        jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel22Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDatPhong)
                                        .addComponent(btnKhachDoan)
                                        .addComponent(btnTraPhong)
                                        .addComponent(btnThemPhong))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel35)
                                .addContainerGap())
                );

                jPanel23.setBackground(new java.awt.Color(204, 255, 204));

                btnDichVu.setBackground(new java.awt.Color(255, 255, 153));
                btnDichVu.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnDichVu.setForeground(new java.awt.Color(255, 51, 51));
                btnDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Favourites.png"))); // NOI18N
                btnDichVu.setText("Dịch vụ");
                btnDichVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnDichVu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                jLabel36.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel36.setText("  Quản Lý Dịch Vụ");

                javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
                jPanel23.setLayout(jPanel23Layout);
                jPanel23Layout.setHorizontalGroup(
                        jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel23Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel23Layout.setVerticalGroup(
                        jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel23Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDichVu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel36)
                                .addContainerGap())
                );

                jPanel24.setBackground(new java.awt.Color(204, 255, 204));

                btnTaiKhoan.setBackground(new java.awt.Color(255, 255, 153));
                btnTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnTaiKhoan.setForeground(new java.awt.Color(255, 51, 51));
                btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Clien list.png"))); // NOI18N
                btnTaiKhoan.setText("Tài khoản");
                btnTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnTaiKhoanActionPerformed(evt);
                        }
                });

                btnNhanVien.setBackground(new java.awt.Color(255, 255, 153));
                btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnNhanVien.setForeground(new java.awt.Color(255, 51, 51));
                btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/staff.png"))); // NOI18N
                btnNhanVien.setText("Nhân viên");
                btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNhanVienActionPerformed(evt);
                        }
                });

                jLabel37.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel37.setText("            Quản Lý Nhân Viên");

                javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
                jPanel24.setLayout(jPanel24Layout);
                jPanel24Layout.setHorizontalGroup(
                        jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel24Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel24Layout.createSequentialGroup()
                                                .addComponent(btnTaiKhoan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnNhanVien)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel24Layout.setVerticalGroup(
                        jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel24Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnTaiKhoan)
                                        .addComponent(btnNhanVien))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel37)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(246, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                tab.addTab("Danh Mục Quản Lý", jPanel3);

                jPanel4.setBackground(new java.awt.Color(204, 255, 255));

                jPanel25.setBackground(new java.awt.Color(204, 255, 204));

                btnBaoCao.setBackground(new java.awt.Color(255, 255, 153));
                btnBaoCao.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnBaoCao.setForeground(new java.awt.Color(255, 51, 51));
                btnBaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report_24.png"))); // NOI18N
                btnBaoCao.setText("Báo cáo");
                btnBaoCao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnBaoCao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                btnCongNo.setBackground(new java.awt.Color(255, 255, 153));
                btnCongNo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnCongNo.setForeground(new java.awt.Color(255, 51, 51));
                btnCongNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Payment.png"))); // NOI18N
                btnCongNo.setText("Công nợ");
                btnCongNo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnCongNo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnCongNo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCongNoActionPerformed(evt);
                        }
                });

                jLabel41.setBackground(new java.awt.Color(255, 255, 255));
                jLabel41.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel41.setText("          Báo Cáo Tổng Hợp");

                javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
                jPanel25.setLayout(jPanel25Layout);
                jPanel25Layout.setHorizontalGroup(
                        jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel25Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel25Layout.createSequentialGroup()
                                                .addComponent(btnBaoCao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCongNo)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel25Layout.setVerticalGroup(
                        jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel25Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBaoCao)
                                        .addComponent(btnCongNo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel41)
                                .addContainerGap())
                );

                jPanel26.setBackground(new java.awt.Color(204, 255, 204));

                btnQuanLyKho.setBackground(new java.awt.Color(255, 255, 153));
                btnQuanLyKho.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnQuanLyKho.setForeground(new java.awt.Color(255, 51, 51));
                btnQuanLyKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delivery-truck-icon.png"))); // NOI18N
                btnQuanLyKho.setText("Quản lý kho");
                btnQuanLyKho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnQuanLyKho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                jLabel39.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel39.setText("    Thống Kê Kho");

                javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
                jPanel26.setLayout(jPanel26Layout);
                jPanel26Layout.setHorizontalGroup(
                        jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel26Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel26Layout.createSequentialGroup()
                                                .addComponent(btnQuanLyKho)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel26Layout.setVerticalGroup(
                        jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel26Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnQuanLyKho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel39)
                                .addContainerGap())
                );

                jPanel27.setBackground(new java.awt.Color(204, 255, 204));

                btnNhatKy.setBackground(new java.awt.Color(255, 255, 153));
                btnNhatKy.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                btnNhatKy.setForeground(new java.awt.Color(255, 51, 51));
                btnNhatKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Notes.png"))); // NOI18N
                btnNhatKy.setText("Nhật ký");
                btnNhatKy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnNhatKy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                jLabel40.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel40.setText("Thống Kê Hệ Thống");

                javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
                jPanel27.setLayout(jPanel27Layout);
                jPanel27Layout.setHorizontalGroup(
                        jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNhatKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                jPanel27Layout.setVerticalGroup(
                        jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel27Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNhatKy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel40)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(749, Short.MAX_VALUE))
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                tab.addTab("Báo Cáo-Thống Kê", jPanel4);

                jPanel20.setBackground(new java.awt.Color(204, 255, 255));

                jPanel28.setBackground(new java.awt.Color(204, 255, 204));

                jButton20.setBackground(new java.awt.Color(255, 255, 153));
                jButton20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jButton20.setForeground(new java.awt.Color(255, 51, 51));
                jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/infor_24.png"))); // NOI18N
                jButton20.setText("Giới thiệu phần mềm");
                jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                jButton21.setBackground(new java.awt.Color(255, 255, 153));
                jButton21.setForeground(new java.awt.Color(255, 51, 51));
                jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Lists.png"))); // NOI18N
                jButton21.setText("Hướng dẫn sử dụng");
                jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jButton21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                jButton22.setBackground(new java.awt.Color(255, 255, 153));
                jButton22.setForeground(new java.awt.Color(255, 51, 51));
                jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Online.png"))); // NOI18N
                jButton22.setText("Kiểm tra phiên bản");
                jButton22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jButton22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
                jPanel28.setLayout(jPanel28Layout);
                jPanel28Layout.setHorizontalGroup(
                        jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel28Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton22)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel28Layout.setVerticalGroup(
                        jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel28Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton20)
                                        .addComponent(jButton21)
                                        .addComponent(jButton22))
                                .addContainerGap(59, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
                jPanel20.setLayout(jPanel20Layout);
                jPanel20Layout.setHorizontalGroup(
                        jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(757, Short.MAX_VALUE))
                );
                jPanel20Layout.setVerticalGroup(
                        jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                tab.addTab("Hỗ Trợ", jPanel20);

                tabs.setTabPlacement(javax.swing.JTabbedPane.LEFT);

                jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bed_72.png"))); // NOI18N
                jLabel7.setText("Phòng");
                jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jPanel12.add(jLabel7);

                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bed_72.png"))); // NOI18N
                jLabel8.setText("Phòng");
                jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jPanel12.add(jLabel8);

                jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bed_72.png"))); // NOI18N
                jLabel9.setText("Phòng");
                jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
                jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jPanel12.add(jLabel9);

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                                .addGap(116, 116, 116))
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
                );

                tabs.addTab("Tầng 1 (Phòng STD)", jPanel6);
                tabs.addTab("Tầng 2(Phòng SUV)", jPanel7);
                tabs.addTab("Tầng 3(Phòng DLX)", jPanel8);
                tabs.addTab("Tầng 4(Phòng SUT)", jPanel9);

                jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(null));

                jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/infor_24.png"))); // NOI18N
                jLabel11.setText("Hế Thống Quản Lý Khách Sạn");

                jLabel12.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
                jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User.png"))); // NOI18N
                jLabel12.setText("Tài khoản : User");

                jLabel13.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
                jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/staff.png"))); // NOI18N
                jLabel13.setText("Chức vụ : Nhân Viên Lễ Tân");

                jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Alarm.png"))); // NOI18N
                jLabel14.setText("12 : 12 :12 AM");

                javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
                jPanel19.setLayout(jPanel19Layout);
                jPanel19Layout.setHorizontalGroup(
                        jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel19Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)
                                .addGap(260, 260, 260)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addContainerGap())
                );
                jPanel19Layout.setVerticalGroup(
                        jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel19Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tab)
                                        .addComponent(tabs)
                                        .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
            // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnCongNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongNoActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_btnCongNoActionPerformed

        private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
                // TODO add your handling code here:
                
        }//GEN-LAST:event_btnTaiKhoanActionPerformed

        private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
                // TODO add your handling code here:
                openNhanVien();

        }//GEN-LAST:event_btnNhanVienActionPerformed

        private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
                // TODO add your handling code here:
                openDangXuat();
        }//GEN-LAST:event_btnDangXuatActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(GiaoDienChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(GiaoDienChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(GiaoDienChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(GiaoDienChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new GiaoDienChinhJFrame().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBaoCao;
        private javax.swing.JButton btnCongNo;
        private javax.swing.JButton btnDangXuat;
        private javax.swing.JButton btnDanhSach;
        private javax.swing.JButton btnDatPhong;
        private javax.swing.JButton btnDichVu;
        private javax.swing.JButton btnDoThatLac;
        private javax.swing.JButton btnDoiMatKhau;
        private javax.swing.JButton btnKhachDoan;
        private javax.swing.JButton btnNgayHetHan;
        private javax.swing.JButton btnNhanVien;
        private javax.swing.JButton btnNhatKy;
        private javax.swing.JButton btnPhongTrong;
        private javax.swing.JButton btnQuanLyKho;
        private javax.swing.JButton btnSapXep;
        private javax.swing.JButton btnTaiKhoan;
        private javax.swing.JButton btnThemPhong;
        private javax.swing.JButton btnThoat;
        private javax.swing.JButton btnTraPhong;
        private javax.swing.JButton jButton20;
        private javax.swing.JButton jButton21;
        private javax.swing.JButton jButton22;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel34;
        private javax.swing.JLabel jLabel35;
        private javax.swing.JLabel jLabel36;
        private javax.swing.JLabel jLabel37;
        private javax.swing.JLabel jLabel39;
        private javax.swing.JLabel jLabel40;
        private javax.swing.JLabel jLabel41;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel10;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel19;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel20;
        private javax.swing.JPanel jPanel21;
        private javax.swing.JPanel jPanel22;
        private javax.swing.JPanel jPanel23;
        private javax.swing.JPanel jPanel24;
        private javax.swing.JPanel jPanel25;
        private javax.swing.JPanel jPanel26;
        private javax.swing.JPanel jPanel27;
        private javax.swing.JPanel jPanel28;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JTabbedPane tab;
        private javax.swing.JTabbedPane tabs;
        // End of variables declaration//GEN-END:variables
}
